### ISSUE TITLE
build in php 7.2

### ISSUE THREAD

**Issue by KpuTuK** [jpauli/php-av#2]
hello!
Errors occur during assembly in PHP 7.2

/root/php-av/av.c: In function 'zif_av_file_get_metadata':
/root/php-av/av.c:465:27: error: expected expression before 'php_av_file'
  ZEND_FETCH_RESOURCE(paf, php_av_file *, &res, -1, AVFILE_RESOURCE_NAME, le_avfile_resource);
                           ^~~~~~~~~~~
/root/php-av/av.c: In function 'zif_av_stream_open':
/root/php-av/av.c:485:27: error: expected expression before 'php_av_file'
  ZEND_FETCH_RESOURCE(paf, php_av_file *, &res, -1, AVFILE_RESOURCE_NAME, le_avfile_resource);
                           ^~~~~~~~~~~
/root/php-av/av.c: In function 'zif_av_stream_get_metadata':
/root/php-av/av.c:512:27: error: expected expression before 'php_av_stream'
  ZEND_FETCH_RESOURCE(pas, php_av_stream *, &res, -1, AVSTREAM_RESOURCE_NAME, le_avstream_resource);

Help please

**Comment by jpauli** [comment]
The Macro API has changed for PHP 7.2.

Have a look at the new macros and send a PR please

**Comment by KpuTuK** [comment]
https://github.com/davidsteinsland/php-av/compare/master...KpuTuK:master
corrected by agreement
https://www.alibabacloud.com/forum/read-405
the assembly is successful

when calling phpinfo (); php falls
but if you comment out
avformat_version () on line 265 then phpinfo () prints

------------------------------
I'm new to c
